# Generated by Django 4.0.3 on 2022-03-21 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SellerApp', '0003_alter_modelseller_companyname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelseller',
            name='email',
        ),
    ]
