# Generated by Django 4.0.3 on 2022-03-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelproductcategory',
            options={'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterField(
            model_name='modelproduct',
            name='category',
            field=models.ManyToManyField(help_text='Kategori', related_name='cats', to='ProductsApp.modelproductcategory', verbose_name='Kategori'),
        ),
    ]
