# Generated by Django 4.0.3 on 2022-03-19 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProductsApp', '0001_initial'),
        ('SellerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelproduct',
            name='seller',
            field=models.ForeignKey(help_text='Mağaza', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='SellerApp.modelseller', verbose_name='Mağaza'),
        ),
    ]
