# Generated by Django 3.2.12 on 2022-03-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsApp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelproduct',
            name='shipping',
            field=models.BooleanField(default=True, help_text='Kargo', verbose_name='Kargo'),
        ),
    ]
