# Generated by Django 4.0.3 on 2022-03-14 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CartApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelcart',
            options={'verbose_name': 'Cart', 'verbose_name_plural': 'Carts'},
        ),
        migrations.AlterModelOptions(
            name='modelcartitem',
            options={'verbose_name': 'Cart Item', 'verbose_name_plural': 'Cart Items'},
        ),
        migrations.AlterModelTable(
            name='modelcart',
            table='Cart',
        ),
        migrations.AlterModelTable(
            name='modelcartitem',
            table='CartItems',
        ),
    ]
