# Generated by Django 4.0.3 on 2022-03-19 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CartApp', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelcartitem',
            old_name='item',
            new_name='product',
        ),
    ]
