# Generated by Django 4.0.3 on 2022-03-17 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FavoritesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelfavorite',
            options={'verbose_name': 'Favorite', 'verbose_name_plural': 'Favorites'},
        ),
        migrations.AlterModelTable(
            name='modelfavorite',
            table='Favorites',
        ),
    ]
