# Generated by Django 4.0.3 on 2022-03-17 12:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FavoritesApp', '0002_alter_modelfavorite_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelfavorite',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Kaydetme Tarihi', verbose_name='Kaydetme Tarihi'),
            preserve_default=False,
        ),
    ]
