# Generated by Django 4.0.3 on 2022-03-14 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProductsApp', '0002_alter_modelproduct_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserApp', '0004_alter_modeladdress_options_alter_modeladdress_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(auto_now_add=True, help_text='Sipariş Tarihi', verbose_name='Sipariş Tarihi')),
                ('address', models.ForeignKey(help_text='Adres', null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserApp.modeladdress', verbose_name='Adres')),
                ('user', models.ForeignKey(help_text='Kullanıcı', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
        migrations.CreateModel(
            name='ModelOrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(help_text='Ürün', on_delete=django.db.models.deletion.CASCADE, to='ProductsApp.modelproduct', verbose_name='Ürün')),
                ('order', models.ForeignKey(help_text='Sipariş', on_delete=django.db.models.deletion.CASCADE, to='OrderApp.modelorder', verbose_name='Sipariş')),
            ],
        ),
    ]
