# Generated by Django 4.0.3 on 2022-03-14 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OrderApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelorder',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterField(
            model_name='modelorder',
            name='user',
            field=models.ForeignKey(help_text='Kullanıcı', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='modelorderitems',
            name='order',
            field=models.ForeignKey(help_text='Sipariş', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='OrderApp.modelorder', verbose_name='Sipariş'),
        ),
        migrations.AlterModelTable(
            name='modelorder',
            table='Orders',
        ),
    ]
