# Generated by Django 4.0.3 on 2022-03-14 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderApp', '0002_alter_modelorder_options_alter_modelorder_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelorderitems',
            options={'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterModelTable(
            name='modelorderitems',
            table='OrderItems',
        ),
    ]
