# Generated by Django 4.0.3 on 2022-03-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderApp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelorderitems',
            name='price',
            field=models.PositiveIntegerField(default=1, help_text='Fiyat', verbose_name='Fiyat'),
            preserve_default=False,
        ),
    ]
