# Generated by Django 4.0.3 on 2022-03-14 13:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('OrderApp', '0003_alter_modelorderitems_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelorder',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Sipariş Id', unique=True, verbose_name='Sipariş Id'),
        ),
    ]
