# Generated by Django 4.0.3 on 2022-03-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeluser',
            name='address',
            field=models.ManyToManyField(blank=True, help_text='Adresler', related_name='addrs', to='UserApp.modeladdress', verbose_name='Adresler'),
        ),
    ]
