# Generated by Django 3.2.12 on 2022-03-26 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CommentApp', '0003_initial'),
        ('LikeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentlikemodel',
            options={'verbose_name': 'CommentLike', 'verbose_name_plural': 'CommentsLikes'},
        ),
        migrations.AlterField(
            model_name='commentlikemodel',
            name='comment',
            field=models.ForeignKey(help_text='Yorum', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='CommentApp.modelcomment', verbose_name='Yorum'),
        ),
        migrations.AlterModelTable(
            name='commentlikemodel',
            table='CommentsLikes',
        ),
    ]
