# Generated by Django 4.0.3 on 2022-03-16 18:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CommentApp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcomment',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
